### GET request to /actuator/health
GET {{baseUrl}}/actuator/health
Accept: application/json
Host: {{host}}


### POST request to /actuator/custom false
POST {{baseUrl}}/actuator/custom
Content-Type: application/json
Host: {{host}}

{
  "healthy": false
}

### POST request to /actuator/custom true
POST {{baseUrl}}/actuator/custom
Content-Type: application/json
Host: {{host}}

{
  "healthy": true
}


### GET request to /actuator/info
GET {{baseUrl}}/actuator/info
Accept: application/json
Host: {{host}}

### GET request to /actuator/health/liveness
GET {{baseUrl}}/actuator/health/liveness
Accept: application/json
Host: {{host}}

### GET request to /actuator/health/readiness
GET {{baseUrl}}/actuator/health/readiness
Accept: application/json
Host: {{host}}

### GET request to /actuator/custom
GET {{baseUrl}}/actuator/custom
Host: {{host}}