### GET request to /actuator/health
GET {{baseUrl}}/messages
Accept: text/event-stream
Host: {{host}}


### POST request to /actuator/custom false
POST {{baseUrl}}/messages
Content-Type: application/json
Host: {{host}}

{
  "origin": "origin",
  "title": "title",
  "message": "message"
}
