### GET request to /actuator/health
GET {{baseUrl}}/messages
Accept: application/json
Host: {{host}}


### POST request to /actuator/custom false
POST {{baseUrl}}/messages
Content-Type: application/json
Host: {{host}}

{
  "recipient": "recipient",
  "origin": "origin",
  "message": "message"
}
