### GET request to /messages
GET {{baseUrl}}/messages
Accept: text/event-stream
Host: {{host}}


### POST request to /messages
POST {{baseUrl}}/messages
Content-Type: application/json
Host: {{host}}

{
  "origin": "origin",
  "title": "title",
  "content": "message",
  "timestamp": "2020-06-29T16:50:40.236Z"
}
