apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: demo-kafka-ui
      context: ui
      docker:
      sync:
        manual:
          - src: "ui/dist/**/*"
            dest: /usr/share/nginx/html
            strip: ui/dist/
    - image: demo-kafka-api
      custom:
        #buildCommand: ./mvnw spring-boot:build-image -Ddocker.image=$IMAGE && docker push $IMAGE
        # as working with a local image, no need to push
        #buildCommand: ./mvnw spring-boot:build-image -Ddocker.image=$IMAGE
        buildCommand: ./gradlew bootBuildImage --imageName=$IMAGE & kind load $IMAGE $IMAGE
        dependencies:
          paths:
            - build.gradle.kts
            - src/main/resources
            - src/main/k8s
            - build/classes
      sync:
        manual:
          - src: "src/main/resources/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: src/main/resources/
          - src: "target/classes/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: target/classes/
deploy:
  kustomize:
    paths:
      - "src/main/k8s/"