spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
          configuration:
            auto.offset.reset: latest
      default-binder: kafka
      bindings:
        input:
          group: demo-kafka
          destination: chat-messages
          contentType: application/json
        output:
          destination: chat-messages
          contentType: application/json

server:
  shutdown: graceful

logging:
  root: warn
  com.github.scalvet: debug