spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
          configuration:
            auto.offset.reset: latest
      #default-binder: kafka
      bindings:
        message-stream-input:
          group: demo-kafka
          destination: messages-topic
          contentType: application/json
          binder: kafka
        message-stream-output:
          destination: messages-topic
          contentType: application/json
          binder: kafka
        #client-stream-input:
        #  binder: kafka
        #client-stream-output:
        #  binder: kafka

server:
  shutdown: graceful

logging:
  root: warn
  com.github.scalvet: debug