apiVersion: apps/v1
kind: StatefulSet
#https://stackoverflow.com/questions/47516355/multi-broker-kafka-on-kubernetes-how-to-set-kafka-advertised-host-name
metadata:
  name: kafka-broker
spec:
  selector:
    matchLabels:
      app: kafka-broker
  serviceName: kafka-cluster
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.12-2.5.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            #- name: KAFKA_ADVERTISED_HOST_NAME
            #  value: "kafka-broker-0.kafka-cluster.default.svc.cluster.local"
            #- name: HOSTNAME_COMMAND
            #  value: "echo ${HOSTNAME}.default.svc.cluster.local"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            #- name: KAFKA_ADVERTISED_LISTENERS
            #  value: "INSIDE://:9092,OUTSIDE://192.168.99.100:31090"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://kafka-broker-0:9092,OUTSIDE://192.168.99.100:31090"
            - name: KAFKA_LISTENERS
              value: "INSIDE://:9092,OUTSIDE://:9094"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"
            - name: KAFKA_CREATE_TOPICS
              value: "messages-topic:2:1"