apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: reactive-chat
resources:
  demo-kafka-deployment.yml
#patchesStrategicMerge:
#  - patch/memorylimit_patch.yml
configMapGenerator:
  - name: demo-kafka-config
    files:
      - config/application.yml