apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  project: demo-kafka
resources:
  - zookeeper-deployment.yml
  - zookeeper-service.yml
  - kafka-deployment.yml
  - kafka-service.yml
  - api-deployment.yml
#patchesStrategicMerge:
#  - patch/memorylimit_patch.yml
configMapGenerator:
  - name: demo-kafka-config
    files:
      - config/application.yml